### ISSUE TITLE
[Bug]: Failed to load url ./styles.postcss in MenuBar.svelte

### ISSUE THREAD

**Issue by xmlking** [sveltinio/sveltin#152]
error after upgrading dependencies  

```
Error: Failed to load url ./styles.postcss (resolved id: ./styles.postcss) in /Users/schintha/Developer/Work/SPA/my-docs/node_modules/.pnpm/@sveltinio+widgets@0.7.6/node_modules/@sveltinio/widgets/dist/components/menubar/MenuBar.svelte. Does the file exist?
    at loadAndTransform (file:///Users/schintha/Developer/Work/SPA/my-docs/node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1/node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21)
    at async instantiateModule (file:///Users/schintha/Developer/Work/SPA/my-docs/node_modules/.pnpm/vite@4.4.9_@types+node@20.7.1/node_modules/vite/dist/node/chunks/dep-df561101.js:55875:10) {
  code: 'ERR_LOAD_URL'
}
```

<img width="454" alt="image" src="https://github.com/sveltinio/sveltin/assets/627951/771ff29c-5549-4f01-93a7-6d3d1da22340">

<img width="1495" alt="image" src="https://github.com/sveltinio/sveltin/assets/627951/e195a7e0-cd70-43c1-9e9a-91ab396a3ac6">

**Comment by indaco** [comment]
@xmlking fixed. Please, update `@sveltinio/widgets` to the latest `v0.7.7`
